spring:
  application:
    name: wifyt
  datasource:
    url: jdbc:postgresql://localhost:5432/wifyt
    username: postgres
    password: swiss18
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/wifytMongo

jwt:
  secret: 893697bccb7900415da500d21449fa161ad85c5cd9b5703f28265c855a24c10c